/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/desktop/AL/pic/prj/al_ip/ddio_out.v
 ** Date	:	2023 06 13
 ** TD version	:	5.0.30786
\************************************************************/

`timescale 1ns / 1ps

module ddio_out ( q, clk, d1, d0, rst );
output 		q;
input  		clk;
input  		d1;
input  		d0;
input  		rst;

		EG_LOGIC_ODDR #(
		.ASYNCRST("DISABLE"))
		oddr (
		.q(q),
		.clk(clk),
		.d1(d1),
		.d0(d0),
		.rst(rst));

endmodule